name: CI Pipeline

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm install

      - name: Executar testes
        run: npm test

      - name: Gerar relatório de testes
        run: |
          mkdir -p reports
          npm test > reports/test-report.txt

      - name: Upload do relatório
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-testes
          path: reports/test-report.txt
